version: '3.1'
services:
  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
    - "5432:5432"
    volumes:
      - "dbvol:/var/lib/postgresql/data"

volumes:
  dbvol: