
server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rede_social
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
